### ISSUE TITLE
Tab focus rect

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#303]
Currently the focus rect for a tab is drawn on all sides, perhaps it would look nicer if it was **not** drawn on the bottom?

Gtk tabs:
![gtk-tab](https://user-images.githubusercontent.com/1141694/38173864-99c55a4c-35bc-11e8-8ae8-b925a405bd43.png)

Current Kvantum style of Communitheme tabs:
![kv-tab](https://user-images.githubusercontent.com/1141694/38173865-a3c0b38e-35bc-11e8-8474-0b2c16f12293.png)

**Comment by madsrh** [comment]
+1 from me. @Feichtmeier is this within your CSS skills?

**Comment by Feichtmeier** [comment]
Searched a while in the code:

this is actually the selection ring for gtk elements
If we change this it is changed everywhere (@nana-4  correct me if this can be done otherwise)

You have to change the tab and then click it again or use the tab button to tab through all the elements.

**Comment by nana-4** [comment]
@Feichtmeier It's possible to change the focus style individually for each element.

It's also possible to reproduce the Kvantum style, but it'll be a very hacky way. :wink: 

![image](https://user-images.githubusercontent.com/9556384/38246216-03e49940-377c-11e8-94d3-fd1265a23a2a.png)

You can try it by pasting the code into the GTK+ Inspector:

```css
notebook:focus header.top tab:checked {
  outline: none;
  border-color: transparent transparent @theme_base_color;
  background-image: image(@theme_base_color), linear-gradient(to bottom, @theme_selected_bg_color, @borders);
  background-origin: padding-box, border-box;
  background-clip: padding-box, border-box;
}
```
